### PR TITLE
Pdf callback : blank pages

### PR DESCRIPTION
**Pull request by MaNuGitH**
First thank you eKoopmans for your excellent work.
I'm using pdf-callback branch to add page numbers into my pdf.
Everything's fine in the pdf up to 11 pages but, when it turns 12 pages, all pages are blank excepting my page numbers... :(
Can you help ?

### CODE REVIEW

**Comment by vitormc1** [comment]
@MaNuGitH  how do you work with pdf object in callback? Im stuck, my objetive is send the pdf file by e-mail.

**Comment by MaNuGitH** [comment]
Hi
here is my code in callback :

    function myCallback(pdf) {
        pdf.setFontSize(9);
        pdf.setFont("arial", "normal");
        pdf.setTextColor(100);
        var number_of_pages = pdf.internal.getNumberOfPages();
        var pdf_pages = pdf.internal.pages;
        for (var i = 1; i < pdf_pages.length; i++) {
            var myFooter = "Page " + i + " / " + number_of_pages;
            pdf.setPage(i);
            pdf.text(myFooter, 730, 1120);
        }
        pdf.save('test.pdf');

2018-01-25 15:15 GMT+01:00 vitormc1 <notifications@github.com>:

**Comment by eKoopmans** [comment]
Hey @MaNuGitH, this is a known issue - canvases have a maximum width/height, after that they stop rendering properly. [More info here](https://github.com/eKoopmans/html2pdf/issues/19#issuecomment-315583260). I don't have any solutions currently, sorry!

**Comment by eKoopmans** [comment]
Hi again, I'm going to close this PR as it's requesting to merge features of `pdf-callback` into the main branch, which isn't my intention. If you have more questions about your issue with maximum canvas size, please follow the link in my comment above. Thanks!

**Comment by jregeimbal** [comment]
This branch was very helpful to me as I needed a way to mutate state when the pdf generation was complete.  I'd recommend this be merged or another solution implemented and released.

**Comment by eKoopmans** [comment]
Following up in case anyone else lands here - the ability to access the PDF object without saving (and much, much more) was added in the "new API" of v0.9.0.

**Comment by thechrisoshow** [comment]
I tried this with the 0.9.0 tag and it didn't work for me. Is it possible for you to undelete the pdf-callback branch?

**Comment by eKoopmans** [comment]
Hi @thechrisoshow, are you sure you were using it correctly? An example of accessing the PDF object:

```js
html2pdf().from(element).toPdf().get('pdf').then(function (pdf) {
    // Use the pdf object as desired, e.g.:
    console.log(pdf);
});
```

The new API adds a lot of functionality, not just the ability to access the PDF object.

**Pull request closed without merging**
