### PR TITLE
notify function added.

### PR DESCRIPTION
**Pull request by marcocelani**
If you want to be notifyed when process is done specify an empty function as last parameter.
E.g. html2pdf(element, opt, () => { console.log('done.'); });
This is usefull, for example, in a modal displaying a loader.

### CODE REVIEW

**Comment by eKoopmans** [comment]
Hey @marcocelani, thanks for the contribution! Yes, this is a useful feature. Right now there's a branch that does a similar task ([pdf-callback](https://github.com/eKoopmans/html2pdf/tree/pdf-callback) sends the final pdf object, when ready, to the specified callback). I've kept it out of the main branch because I'm planning to adjust the API to add promise/callback support and more customization at various stages of the process.

For the same reason, I won't be merging this in, but I'll let you know as soon as the new API is ready!

**Comment by marcocelani** [comment]
Hi @eKoopmans! Thanks for the reply, it is a good news. Great job!

**Comment by eKoopmans** [comment]
Hi, I have just pushed a new branch, [new-api](https://github.com/eKoopmans/html2pdf/tree/new-api), which is ready for testing! [The readme](https://github.com/eKoopmans/html2pdf/tree/new-api#advanced-usage) has all the information on the new API. Please let me know if there are any problems with it - I want to make sure it's stable before merging into master!

This would replace the 'notify' function with a Promise:

```js
html2pdf().from(element).save().then(function () {
  // Your notify function.
});
```

**Comment by eKoopmans** [comment]
Closing, v0.9.0 added the requested feature.

**Pull request closed without merging**
